server:
  port: 8081
  servlet:
    session:
      timeout: 600s
spring:
  session:
    redis:
      namespace: session:redis
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/blogger-dev?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false



