server:
  port: 8081
  servlet:
    session:
      timeout: 600s
spring:
  session:
    redis:
      namespace: session.redis
    jdbc:
      initialize-schema: always
      schema: classpath:/sql/SESSION.sql
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/blogger-dev
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

